version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: test_cases
    ports:
      - "65432:5432"
    restart: always

  web:
    image: flask-app:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      network: "host"
    environment:
      DATABASE_SERVER: "db:5432"
    ports:
      - "8000:8000"
    restart: always
